### ISSUE TITLE
Consider making API more robust by returning enum from `len`

### ISSUE THREAD

**Issue by hannobraun** [xoac/static-bytes#1]
One thing I found when using this API is that it's easy to accidentally forget handling overflows. Yes, `try_into_bytes` returns a result, but you don't actually have to call that (the data has already been written into the wrapped slice, where you need it).

One idea that would make my use case more robust:
1. Rename `len` to `bytes_written` (optional, but I think keeping `len` while implementing the rest of this suggestions would cause confusion).
2. Return enum `BytesWritten` from `bytes_written`, with the variants `BytesWritten::Nominal(usize)` and `BytesWritten::Overflow(usize)` (not sure if those are the best names). That way, the user is always forced to check for overflow.

What do you think?

**Comment by xoac** [comment]
If this problem exists it needs to be resolve by other structures similar to `heapless::Vec<_, _>` where you don't have directly access to memory. One of the aims of static-bytes is to resolve boilerplate. returning enum from `bytes_written()` will make this as complicated as at the beginning. But `bytes_written()` is a much much better name than `len()` and I will rename it anyway.

I have tried to test your problem:
```    #[test]
    fn issue_1() {
        let mut static_data = [0u8; 32];
        let mut safe_slice = SafeBytesSlice::from(&mut static_data[..]);

        fill_with_random(&mut safe_slice, 32);
        assert_eq!(safe_slice.is_exceed(), false);

        let _output = &static_data[..safe_slice.len()];
    }
```
And I have got compile-time error:
```
error[E0502]: cannot borrow `static_data` as immutable because it is also borrowed as mutable
   --> src/bytes_slice.rs:225:24
    |
220 |         let mut safe_slice = SafeBytesSlice::from(&mut static_data[..]);
    |                                                        ----------- mutable borrow occurs here
...
225 |         let _output = &static_data[..safe_slice.len()];
    |                        ^^^^^^^^^^^   ---------- mutable borrow later used here
    |                        |
    |                        immutable borrow occurs here

error: aborting due to previous error
```

Can you provide a minimal example when rust allows your incorrect code to compile?

**Comment by xoac** [comment]
I have this minimal example. 
```rust
    #[test]
    fn issue_1() {
        let mut static_data = [0u8; 32];
        let mut safe_slice = SafeBytesSlice::from(&mut static_data[..]);

        fill_with_random(&mut safe_slice, 32);
        assert_eq!(safe_slice.is_exceed(), false);
        let output_len = safe_slice.bytes_written();
        drop(safe_slice);

        let _output = &static_data[..output_len];
    }
```

But in my opinion, this is not how people write code (argument with :zero:  point value)
I will not accept enum from `bytes_written()` instead there can be done solutions:
- remove `bytes_written()` - is this function necessary?
- panic in debug
- panic in debug and release
- ~instead of returning `usize` return `&'a usize` and prevent this error at compile time. (I would need to test it)~

Waiting for your opinion! And love this problem catch.

**Comment by hannobraun** [comment]
Sorry for the late reply. I see you already made `bytes_written` private, but for the sake of completeness, here's the example that motivated this issue. This is an excerpt from my work-in-progress branch of the [DW1000 driver](https://github.com/braun-embedded/rust-dw1000/tree/master/dw1000):

``` rust
// Prepare transmitter
let mut len = 0;
self.ll
    .tx_buffer()
    .write(|w| {
        let mut buffer = static_bytes::SafeBytesSlice::new(w.data());
        frame.encode(&mut buffer, mac::frame::WriteFooter::No);
        // Overflow is not handled here
        len += buffer.len();
        w
    })?;
```

This uses the low-level driver API to write data into the transmit buffer. There are two things to consider here:
- Accessing the low-level driver API involves a closure, so dropping `buffer` happens naturally.
- I don't need to ever access `w.data()` again, as that buffer is handled by hardware. I only need to access the number of bytes written to it, to let the hardware know how many bytes to send.

I'm closing this issue, as it is no longer possible to accidentally use an invalid `len`/`bytes_written` value. My code is a bit more complicated now than before (due to having to match against `try_into_bytes`), but that is only because the implicit panic from before is an explicit error now, which is a good thing.

**Comment by xoac** [comment]
I wanted to publish `0.1.0` adding more methods is still an option. I decided to remove `len()`/`bytes_written()` since it can be added without breaking changes. 

In my opinion, `static_bytes` is lacking structs like `Bytes`/`Buffer` that will own inner fixed amount of data and imple `bytes::BufMut`.
