### ISSUE TITLE
Dependency on `bytes` is out of date

### ISSUE THREAD

**Issue by hannobraun** [xoac/static-bytes#2]
`bytes` 0.6.0 has been release recently: https://crates.io/crates/bytes

I looked into updating the dependency, but the changes all seem to be about soundness and `unsafe`. Unfortunately I don't have the time right now to figure this out to a degree that would provide any confidence in my work here.

**Comment by xoac** [comment]
Sorry for waiting long. Closed with #3

**Comment by hannobraun** [comment]
Not a problem, thank you!
